name: couchsurfing_social
description: "Couchsurfing Flutter Exercise"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

  get: ^5.0.0-release-candidate-5
  logger: ^2.0.2+1
  cached_network_image: ^3.3.1
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  enum_to_string: ^2.0.1
  readmore: ^2.2.0
  timeago: ^3.6.0
  auto_size_text: ^3.0.0
  auto_size_text_field: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/